/*
* This file is was produced as part of a research project by Lucas Vancina
* lnv
* This is the unittest the ngap_e2_notifier class. It was generated by ChatGPT
*   and edited by Lucas Vancina.
*/

#include "lib/ngap/ngap_e2_notifier.h"
#include <gtest/gtest.h>

using namespace srsran;

// Test fixture
class NgapE2NotifierTest : public ::testing::Test {
protected:
    ngap_e2_notifier notifier;
};

// Test that push_message stores a message and activates the notifier
TEST_F(NgapE2NotifierTest, ReportMessagesActivatesNotifier) {
    byte_buffer msg = {'H', 'e', 'l', 'l', 'o'};
    EXPECT_EQ(notifier.is_active(), false);
    notifier.push_message(msg.copy());
    std::deque<byte_buffer> out_queue = {};
    short num_messages = notifier.report_messages(out_queue);
    EXPECT_EQ(notifier.is_active(), true);
    EXPECT_EQ(num_messages, 1);
    EXPECT_EQ(out_queue[0], msg);
}

// Test that get_next_message retrieves messages in FIFO order
TEST_F(NgapE2NotifierTest, MessageOrdering) {
    byte_buffer msg1 = {'1'};
    byte_buffer msg2 = {'2'};
    notifier.push_message(msg1.copy());
    notifier.push_message(msg2.copy());

    std::deque<byte_buffer> tmp_messages = {};

    notifier.report_messages(tmp_messages);
    auto out1 = tmp_messages[0].copy();
    auto out2 = tmp_messages[1].copy();

    // auto out1 = std::move(tmp_messages.front());

    EXPECT_EQ(out1, msg1);
    EXPECT_FALSE(out1.empty());
    EXPECT_EQ(out2, msg2);
    EXPECT_FALSE(out2.empty());
    EXPECT_TRUE(notifier.empty());
}

// Test that get_next_message on empty queue returns default-constructed message
TEST_F(NgapE2NotifierTest, GetNextMessageOnEmpty) {
    EXPECT_TRUE(notifier.empty());
    byte_buffer out = notifier.get_next_message();
    EXPECT_EQ(out.length(), 0);
}
